### ISSUE TITLE
Can not file extracted npy file

### ISSUE THREAD

**Issue by VOM7HC** [moharamfatema/graduation-project#2]
In file `UBI_splitting.ipynb` code line:
`xmap = np.memmap(ROOT+'/x.npy',dtype=dtype, shape=shape_x, mode=mode)`
Error code:
`FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Datasets/UBI_FIGHTS/extracted/x.npy'`

Then I back to file `UBI_Extraction.ipynb` can't file code generate `x.npy` file, only `y.npy`.

Could you give me more detail the code base?

**Comment by moharamfatema** [comment]
In order to extract all videos and labels in the UBI dataset, you will need to call the function `packets_from_paths` from the `Extractor` class and pass the suitable parameters.

**Comment by WesleyKhoiVo** [comment]
I called `packets_from_paths` before my issue with code
`ext.packets_from_paths(video_paths, annot_paths, OUT)`
Result is:
`FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Datasets/UBI_FIGHTS/extracted/x.npy'`

Since `x.npy` never created but it need to loading numpy file before saving?

**Comment by WesleyKhoiVo** [comment]
Solution: create folder `extracted` by hand before run code 🤣
